// skill logos
export const skillOptions = [
    { name: "HTML", logo: "/logos/html.png" },
    { name: "CSS", logo: "/logos/css.webp" },
    { name: "JavaScript", logo: "/logos/js.svg" },
    { name: "TypeScript", logo: "/logos/ts.png" },
    { name: "React", logo: "/logos/react.png" },
    { name: "Angular", logo: "/logos/angular.png" },
    { name: "Svelte", logo: "/logos/svelte.png" },
    { name: "Next.js", logo: "/logos/nextjs.png" },
    { name: "Redux", logo: "/logos/redux.png" },
    { name: "SASS", logo: "/logos/sass.png" },
    { name: "Node.js", logo: "/logos/node.png" },
    { name: "Express.js", logo: "/logos/express.png" },
    { name: "Vue.js", logo: "/logos/vue.png" },
    { name: "Tailwind CSS", logo: "/logos/tailwind.png" },
    { name: "Python", logo: "/logos/python.png" },
    { name: "Django", logo: "/logos/django.webp" },
    { name: "Flask", logo: "/logos/flask.png" },
    { name: "TensorFlow", logo: "/logos/tensorflow.png" },
    { name: "PyTorch", logo: "/logos/pytorch.png" },
    { name: "Numpy", logo: "/logos/numpy.png" },
    { name: "Pandas", logo: "/logos/pandas.png" },
    { name: "Seaborn", logo: "/logos/seaborn.png" },
    { name: "OpenCV", logo: "/logos/opencv.png" },
    { name: "Scikit Learn", logo: "/logos/scikit.png" },
    { name: "Java", logo: "/logos/java.png" },
    { name: "Spring", logo: "/logos/spring.png" },
    { name: "Spring Boot", logo: "/logos/springboot.png" },
    { name: "GraphQL", logo: "/logos/graphql.png" },
    { name: "NGINX", logo: "/logos/nginx.png" },
    { name: "C++", logo: "/logos/cpp.png" },
    { name: "C", logo: "/logos/c.png" },
    { name: "C#", logo: "/logos/csharp.png" },
    { name: "GoLang", logo: "/logos/golang.png" },
    { name: "PHP", logo: "/logos/php.png" },
    { name: "Ruby", logo: "/logos/ruby.png" },
    { name: "Rust", logo: "/logos/rust.png" },
    { name: "Haskell", logo: "/logos/haskell.png" },
    { name: "Flutter", logo: "/logos/flutter.png" },
    { name: "React Native", logo: "/logos/reactnative.webp" },
    { name: "Dart", logo: "/logos/dart.png" },
    { name: "Kotlin", logo: "/logos/kotlin.png" },
    { name: "MongoDB", logo: "/logos/mongodb.webp" },
    { name: "MySQL", logo: "/logos/mysql.png" },
    { name: "PostgreSQL", logo: "/logos/postgresql.png" },
    { name: "Redis", logo: "/logos/redis.png" },
    { name: "AWS", logo: "/logos/aws.png" },
    { name: "Azure", logo: "/logos/azure.png" },
    { name: "Google Cloud", logo: "/logos/gc.png" },
    { name: "Docker", logo: "/logos/docker.webp" },
    { name: "Kubernetes", logo: "/logos/kubernetes.png" },
    // add more skills here
];